app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/code
  ports:
    - "3000:3000"
  links:
    - postgres
  env_file: .env
postgres:
  image: postgres
  ports:
    - "5432"