defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: 
  host: postgres
  port: 5432


development:
  <<: *defaults
  database: print_hub_development

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'print_hub' %>
  password: <%= ENV['TRAVIS'] ? '' : 'print_hub' %>
  database: print_hub_test

production:
  <<: *defaults
  database: print_hub_production

staging:
  <<: *defaults
  database: print_hub_staging

#Abaco conn
abaco_defaults: &abaco_defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: abaco
  password: abaco

abaco_development:
  <<: *abaco_defaults
  database: abaco_development

abaco_production:
  <<: *abaco_defaults
  database: abaco_production

abaco_test:
  <<: *abaco_defaults
  database: abaco_test
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'print_hub' %>
  password: <%= ENV['TRAVIS'] ? '' : 'print_hub' %>
